# Generated by Django 4.1 on 2023-05-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
