# Generated by Django 4.2.1 on 2023-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
